from maya.OpenMaya import *
from maya.OpenMayaAnim import *
from maya.OpenMayaCloth import *
from maya.OpenMayaFX import *
from maya.OpenMayaMPx import *
from maya.OpenMayaUI import *
from maya.OpenMayaRender import *
from typing import Any, Optional

class SafeApiPtr:
    scriptUtil: Any = ...
    size: Any = ...
    def __init__(self, valueType: str, scriptUtil: MScriptUtil=..., size: int=..., asTypeNPtr: bool=...) -> None: ...
    def __call__(self): ...
    def get(self): ...
    def set(self, value: Any): ...
    def __getitem__(self, index: Any): ...
    def __setitem__(self, index: Any, value: Any): ...
    def __len__(self): ...

def isValidMObjectHandle(obj: Any): ...
def isValidMObject(obj: Any): ...
def isValidMPlug(obj: Any): ...
def isValidMDagPath(obj: Any): ...
def isValidMNode(obj: Any): ...
def isValidMDagNode(obj: Any): ...
def isValidMNodeOrPlug(obj: Any): ...
def toMObject(nodeName: Any): ...
def toApiObject(nodeName: Any, plugs: bool=..., comps: bool=..., dagPlugs: bool=...) -> None: ...
def toMDagPath(nodeName: Any): ...
def toMPlug(plugName: Any): ...
def toComponentMObject(dagPath: Any): ...
def MObjectName(obj: Any): ...
def nameToMObject(*args: Any): ...
def MItNodes(*args: Any, **kwargs: Any) -> None: ...
def MItGraph(nodeOrPlug: Any, *args: Any, **kwargs: Any) -> None: ...
def MItDag(root: Optional[Any] = ..., *args: Any, **kwargs: Any) -> None: ...
def getPlugValue(plug: Any): ...
