from typing import Any

def currentTime(*args: Any, **kwargs: Any): ...
def getCurrentTime(): ...
def setCurrentTime(time: Any): ...
def listAnimatable(*args: Any, **kwargs: Any): ...
def keyframe(*args: Any, **kwargs: Any): ...
def deformer(*args: Any, **kwargs: Any): ...

cmd: Any

def ikHandle(*args: Any, **kwargs: Any): ...
def aimConstraint(*args: Any, **kwargs: Any): ...
def animCurveEditor(*args: Any, **kwargs: Any): ...

animDisplay: Any

def animLayer(*args: Any, **kwargs: Any): ...

animView: Any
applyTake: Any
autoKeyframe: Any
backgroundEvaluationManager: Any
bakeClip: Any

def bakeDeformer(*args: Any, **kwargs: Any): ...
def bakeResults(*args: Any, **kwargs: Any): ...
def bakeSimulation(*args: Any, **kwargs: Any): ...

bindSkin: Any

def blendShape(*args: Any, **kwargs: Any): ...

blendShapeEditor: Any

def blendShapePanel(*args: Any, **kwargs: Any): ...
def blendTwoAttr(*args: Any, **kwargs: Any): ...
def boneLattice(*args: Any, **kwargs: Any): ...
def bufferCurve(*args: Any, **kwargs: Any): ...

buildBookmarkMenu: Any
buildKeyframeMenu: Any

def character(*args: Any, **kwargs: Any): ...
def characterMap(*args: Any, **kwargs: Any): ...

characterize: Any

def choice(*args: Any, **kwargs: Any): ...

clip: Any
clipEditor: Any
clipMatching: Any
clipSchedule: Any

def clipSchedulerOutliner(*args: Any, **kwargs: Any): ...
def cluster(*args: Any, **kwargs: Any): ...
def combinationShape(*args: Any, **kwargs: Any): ...

connectJoint: Any

def controller(*args: Any, **kwargs: Any): ...

copyDeformerWeights: Any
copyFlexor: Any

def copyKey(*args: Any, **kwargs: Any): ...

copySkinWeights: Any

def cutKey(*args: Any, **kwargs: Any): ...
def dagPose(*args: Any, **kwargs: Any): ...

defineDataServer: Any
defineVirtualDevice: Any

def deformableShape(*args: Any, **kwargs: Any): ...

deformerWeights: Any

def deltaMush(*args: Any, **kwargs: Any): ...

deviceManager: Any
disconnectJoint: Any
dopeSheetEditor: Any

def dropoffLocator(*args: Any, **kwargs: Any): ...

effector: Any
enableDevice: Any
evaluationManager: Any
evaluator: Any
filterCurve: Any
findDeformers: Any

def findKeyframe(*args: Any, **kwargs: Any): ...
def flexor(*args: Any, **kwargs: Any): ...
def flow(*args: Any, **kwargs: Any): ...

freezeOptions: Any

def geomBind(*args: Any, **kwargs: Any): ...
def geometryConstraint(*args: Any, **kwargs: Any): ...

ghosting: Any
hikGlobals: Any
ikHandleDisplayScale: Any

def ikSolver(*args: Any, **kwargs: Any): ...
def ikSystem(*args: Any, **kwargs: Any): ...

ikSystemInfo: Any
ikfkDisplayMethod: Any
insertJoint: Any

def joint(*args: Any, **kwargs: Any): ...
def jointCluster(*args: Any, **kwargs: Any): ...

jointDisplayScale: Any

def jointLattice(*args: Any, **kwargs: Any): ...
def keyTangent(*args: Any, **kwargs: Any): ...
def keyframeOutliner(*args: Any, **kwargs: Any): ...
def keyframeStats(*args: Any, **kwargs: Any): ...
def keyingGroup(*args: Any, **kwargs: Any): ...
def lattice(*args: Any, **kwargs: Any): ...

marker: Any
mimicManipulation: Any
mirrorJoint: Any
movIn: Any

def movOut(*args: Any, **kwargs: Any): ...

movieInfo: Any

def mute(*args: Any, **kwargs: Any): ...
def nonLinear(*args: Any, **kwargs: Any): ...
def normalConstraint(*args: Any, **kwargs: Any): ...
def orientConstraint(*args: Any, **kwargs: Any): ...
def pairBlend(*args: Any, **kwargs: Any): ...
def parentConstraint(*args: Any, **kwargs: Any): ...
def pasteKey(*args: Any, **kwargs: Any): ...

pathAnimation: Any
percent: Any
play: Any
playbackOptions: Any
playblast: Any

def pointConstraint(*args: Any, **kwargs: Any): ...
def pointOnPolyConstraint(*args: Any, **kwargs: Any): ...
def poleVectorConstraint(*args: Any, **kwargs: Any): ...

polyUniteSkinned: Any
pose: Any
poseEditor: Any

def posePanel(*args: Any, **kwargs: Any): ...

readTake: Any
recordDevice: Any
removeJoint: Any
reorderDeformers: Any
reroot: Any
rotationInterpolation: Any

def scaleConstraint(*args: Any, **kwargs: Any): ...
def scaleKey(*args: Any, **kwargs: Any): ...
def sculpt(*args: Any, **kwargs: Any): ...

sculptTarget: Any

def sequenceManager(*args: Any, **kwargs: Any): ...

setDrivenKeyframe: Any
setInfinity: Any
setKeyPath: Any
setKeyframe: Any
setKeyframeBlendshapeTargetWts: Any
shapeEditor: Any

def shapePanel(*args: Any, **kwargs: Any): ...
def shot(*args: Any, **kwargs: Any): ...

shotRipple: Any

def simplify(*args: Any, **kwargs: Any): ...

skeletonEmbed: Any

def skinCluster(*args: Any, **kwargs: Any): ...

skinPercent: Any

def snapKey(*args: Any, **kwargs: Any): ...
def snapshot(*args: Any, **kwargs: Any): ...
def softMod(*args: Any, **kwargs: Any): ...

sound: Any
substituteGeometry: Any

def tangentConstraint(*args: Any, **kwargs: Any): ...
def tension(*args: Any, **kwargs: Any): ...
def textureDeformer(*args: Any, **kwargs: Any): ...
def timeEditor(*args: Any, **kwargs: Any): ...
def timeEditorAnimSource(*args: Any, **kwargs: Any): ...

timeEditorBakeClips: Any

def timeEditorClip(*args: Any, **kwargs: Any): ...

timeEditorClipLayer: Any
timeEditorClipOffset: Any
timeEditorComposition: Any

def timeEditorPanel(*args: Any, **kwargs: Any): ...
def timeEditorTracks(*args: Any, **kwargs: Any): ...
def timeWarp(*args: Any, **kwargs: Any): ...

ubercam: Any
volumeBind: Any

def wire(*args: Any, **kwargs: Any): ...

wrinkle: Any
writeTake: Any
