from typing import *
from builtins import str
from typing import Any, Optional

sep: Any

def source(file: Any, searchPath: Iterable[str]=..., recurse: bool=...) -> None: ...
def getMayaLocation(version: bool=...) -> Optional[str]: ...
def getMayaAppDir(versioned: bool=...) -> Optional[str]: ...
def getUserPrefsDir(): ...
def getUserScriptsDir(): ...
def executeDeferred(func: Any, *args: Any, **kwargs: Any) -> None: ...
def recurseMayaScriptPath(roots: Union[str, List[str], Tuple[str]]=..., verbose: bool=..., excludeRegex: str=..., errors: Any=..., prepend: Any=...) -> None: ...
