from typing import Any, Optional

def formatwarning(message: Any, category: Any, filename: Any, lineno: Any, line: Optional[Any] = ...): ...

class PymelBaseWarning(Warning): ...
class ExecutionWarning(UserWarning, PymelBaseWarning): ...
class PymelBaseDeprecationWarning(PymelBaseWarning): ...
class PymelFutureWarning(FutureWarning, PymelBaseDeprecationWarning): ...
class MayaDeprecationWarning(DeprecationWarning, PymelBaseDeprecationWarning): ...

def warn(*args: Any, **kwargs: Any): ...
def deprecated(funcOrMessage: Optional[Any] = ..., className: Optional[Any] = ..., baseMessage: str = ..., warningType: Any = ...): ...
def maya_deprecated(funcOrMessage: Optional[Any] = ..., className: Optional[Any] = ..., baseMessage: str = ..., warningType: Any = ...): ...
