from typing import Any, Optional

def decorated(origFunc: Any, newFunc: Any, decoration: Optional[Any] = ...) -> None: ...
def decorator(func: Any): ...
def format_signature(args: Any = ..., varargs: Optional[Any] = ..., varkw: Optional[Any] = ..., defaults: Optional[Any] = ...): ...
def interface_wrapper(doer: Any, args: Any = ..., varargs: Optional[Any] = ..., varkw: Optional[Any] = ..., defaults: Optional[Any] = ...): ...
