from typing import Any

def appendEnv(env: str, value: str) -> None: ...
def prependEnv(env: str, value: str) -> None: ...
def getEnv(env: str, default: Any=...) -> None: ...
def getEnvs(env: str, default: Any=...) -> List[str]: ...
def putEnv(env: str, value: str) -> None: ...
def refreshEnviron() -> None: ...
def executableOutput(exeAndArgs: Any, convertNewlines: bool=..., stripTrailingNewline: bool=..., returnCode: bool=..., input: str=..., **kwargs: Any) -> None: ...
def shellOutput(shellCommand: Any, convertNewlines: bool=..., stripTrailingNewline: bool=..., returnCode: bool=..., input: str=..., **kwargs: Any) -> None: ...
